project:
  type: book
  output-dir: docs

title-block-author-single: "Instructor"
title-block-published: "Semester"

book:
  title: "Social Psychology Lab Manual"
  subtitle: "PSYC BC2137"
  author: "Professor Rob Brotherton"
  date: "1/31/2023"
  date-format: "[Spring 2023]"
  chapters:
    - index.qmd
    - lab-1.qmd
    - lab-2.qmd
    - lab-3.qmd
    - lab-4.qmd
    - lab-5.qmd
    - lab-6.qmd
    - lab-7.qmd
    - lab-8.qmd
    - lab-9.qmd
    - lab-10.qmd
    - lab-11.qmd
    - lab-12.qmd
    - lab-13.qmd
  appendices:
    - x-reading-research.qmd
    - x-searching-the-literature.qmd
    - x-statistics.qmd
    - a-consent-form.qmd
    - a-debrief.qmd
    - a-writing-a-report.qmd
  downloads: pdf
  # sidebar:
  #   tools:
  #     - icon: github
  #       href: https://github.com/robbrotherton/bc2137/

toc-depth: 1
number-depth: 0

# comments:
#     hypothesis:
#       theme: clean
#       openSidebar: false

crossref:
  appendix-title: Appendix

format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark:  [darkly, custom.scss]
  pdf:
    # title: Social Psychology Lab Manual
    documentclass: scrreprt
    classoption: twoside
    include-in-header:
      text: |
        \newcommand*\cleartoleftpage{%
        \clearpage
        \ifodd\value{page}\hbox{}\newpage\fi
        }



