project:
  type: book
  output-dir: docs
  resources: syllabus.pdf
  pre-render: _render_syllabus.r

title-block-author-single: "Instructor"
title-block-published: ""

book:
  title: "Social Psychology Lab Handbook"
  subtitle: |
    | Barnard College
    | Department of Psychology
    | PSYC BC2137
  # author: "Professor Rob Brotherton"
  date: "1/31/2023"
  date-format: "[Fall 2023]"

  chapters:
    - index.qmd
    - part: "Project 1: Correlation"
      chapters:
        - lab-2.qmd
        - lab-3.qmd
        - lab-4.qmd
        - lab-5.qmd
    - part: "Project 2: ANOVA"
      chapters:
        - lab-6.qmd
        - lab-7.qmd
        - lab-8.qmd
        - lab-9.qmd
    - part: "Project 3: Own design"
      chapters:
        - lab-10.qmd
        - lab-11.qmd
        - lab-12.qmd
  appendices:
    - appendix-r-basics.qmd
    - appendix-describing-data.qmd
    - appendix-correlation.qmd
    - appendix-rubric.qmd

toc-depth: 3
number-depth: 0
number-sections: false

# comments:
#     hypothesis:
#       theme: clean
#       openSidebar: false

crossref:
  appendix-title: Appendix

format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark:  [darkly, custom.scss]
    link-external-newwindow: true


