# Example debriefing document {#sec-debrief}

__Here’s an example debriefing from a study on national stereotypes—a potentially sensitive topic. Notes are in [*italics*].__

[*First, thank participants and give them a general idea of what the study was about. Put things as plainly as possible; participants are likely unfamiliar with psychological jargon*]

Your participation is now complete. Thank you! This study was an investigation into the function of stereotypes. Many people have national stereotypes. For example, you can all probably imagine a stereotypical image of an English person or a German person or an American etc. Yet these stereotypes are not necessarily always the same in every situation. Sometimes people might vary their national stereotypes as a means of trying to justify their prior discriminatory behaviour. We want to see whether this might be true.

[*Next, give a full account of everything that participants were asked to do, and what purpose it served. Remember, if you use a between-participants design participants will be unaware of the conditions they were not exposed to, so make sure everyone understands both what they were asked to do and what other participants were asked to do. Take special care if any deception was involved or if you weren’t forthcoming about the true purpose of certain things. Participants should not be left with any misconceptions about your research*]

So in this experiment we measured the national stereotypes of everyone and this acted as our main dependent variable. This was achieved by 2 methods. First, everyone completed the questions regarding how representative a list of traits was of a particular group (i.e. English and German). Second, the memory recall task was used to evaluate the extent to which people were activating stereotypes to help their recall. Better recall of stereotype-consistent words compared to stereotype-inconsistent words was taken as evidence of stereotype use. There were 3 simple manipulations in the overall design of the study. These were all included to encourage participants to engage in discriminatory behaviour. First, in all sessions we provided you with false information regarding a made-up study of the allocation strategies favoured by English students from different Universities. Second, in some sessions we gave you the opportunity to show discriminatory behaviour. Finally, in some sessions were asked you to offer an explanation of why English students might favour their own group.

[*After describing the method, describe your anticipated findings, and what such findings would demonstrate about human psychology*]

We anticipate that participants who showed high levels of discrimination will produce different national stereotypes and activate national stereotypes more compared to participants who showed low levels of discrimination. If this is true, then our original suspicion regarding the justificatory function of stereotypes might be true.

[*Lastly, remind participants who to contact with any remaining questions, and thank them once more*]

Please contact [*researchers*] at the following e-mail address […] if you have any questions regarding this study.

THANK YOU AGAIN FOR YOUR PARTICIPATION!
