
# Tips for Reading Research Papers {#sec-reading}

The following suggestions are guidelines for approaching research reports when you are searching the scholarly literature for previous studies relevant to your own research topic. These journal articles are usually written for other experts in the field and may contain terminology and analyses that you are unfamiliar with. Most articles that report new empirical findings have a standard format, in which the material is sectioned into an Abstract, Introduction, Method, Results, and Discussion. This means you should know where to find key information and allows for a systematic approach. You might need to revisit each section to come to a full understanding of the article. 

Note that the most effective approach to reading and note-taking may be different when working on a project like this than when you are assigned specific readings for class; here I’m assuming that you are searching an unfamiliar literature and need to quickly evaluate whether the many papers you encounter are relevant enough to spend more time reading and evaluating in detail (rather than, say, critically evaluating a set article).

Note also that there are many possible ways to approach research articles. If you have a favorite method, or a hint for fellow students, please pass it on so that your suggestions can be incorporated.


## Step 0. Read the title
The title of a paper is the first thing you’ll see in your search results. Much of the time it should be clear from the title alone whether examining the paper further will be a good use of your time. If it seems promising, or if you’re not yet sure, move on to the Abstract.

## Step 1. Read the Abstract
Even though it may be confusing if you are unfamiliar with the subject matter, the abstract will give you a quick overview of the material in the article. Try to determine the overall point of the paper before starting the body of the report. Between the title and Abstract of a paper, you should be able to decide in less than a minute or so whether to continue with a paper or to discard it as irrelevant to you. For this lab, you can be ruthless; your time is very limited and so you only want to spend it on research articles that will (hopefully) make the greatest possible contribution to your proposal.

## Step 2. Skim, then read, through the Introduction
Don’t spend too much time on the Introduction, unless the Abstract is overly complicated and you don’t understand the point of the experiment. Begin by trying to find the hypothesis (usually near the end of the Introduction), so that you can understand where the arguments are leading. Then, read the entire Introduction and see what you can get from it. In a new area, it usually takes at least 2 readings before you understand it fully.

## Step 3. Go to the Method section to get the information to better understand the Introduction
In general, the Method section should be understood fully in terms of why each step is conducted to investigate the hypotheses. While reading through the Method section you may need to review some parts of the Introduction.

## Step 4. Introduction and hypothesis revisited
If at this point the study still seems relevant to you, it’s worth stopping for a moment to think about what results you expect given the original hypothesis. See if you can predict what the researchers will find and roughly how they might report it. Would there be graphs; what would they look like? Seeing how your predictions pan out will give you a sense of how well you understand the research so far.

## Step 5. Read though the relevant Results
Read through the entire results section, but don’t agonize over it—if you haven’t had a course in statistics it probably won’t make much sense, and even then you may encounter more advanced statistical techniques. If there are Figures, focus on them and the associated captions, text and analyses. (And see the Summary of Basic Statistics in Appendix C).

## Step 6. Skim, then read, the Discussion
First, skim thought the Discussion section to find detailed confirmation of the hypotheses. There should be nothing surprising in the Discussion, if you were able to surmise the gist of the report while reading the previous sections.

## Step 7. Take notes
After going through the whole article in this fashion first, read through it again while taking notes. Your notes should include a summary of the hypotheses, a brief methodology, and summary of results, and a conclusion. Also, point out what you think are the most important strengths and weaknesses of the study.

