# Lab 2: Project Planning {.unnumbered}

In this session we will begin the first project of the course: performing a correlational analysis using the ANES 2020 dataset. By the end of the session you will have a plan for your analysis.


### Goals

-   Understand the purpose of a correlational design
-   Identify the variables for your analysis
-   Read some relevant research
-   Articulate your hypothesis


## Report template

You'll use a template to eventually write up your individual report paper (including the code that you will start writing next week to analyze the data). The template exists in posit.cloud, the cloud-based RStudio interface I mentioned last week. A link to to join the posit.cloud 'space' for the course will be emailed separately.

Once you have joined the 'space' you should see one link there called "Projects." Click into it, and then look for "report_1.qmd" under the "Files" tab in the bottom-right pane. Click that file to open up the first project template.

I strongly encourage you to start keeping notes for your Intro in that document as you start forming your ideas for the project today.


## Project overview


### Correlational designs

With this project you will examine a correlation between social psychological constructs using real survey data.

A *correlation* refers an association between two things. It is a statement of a statistical relationship--a general tendency, rather than a rigid law. To say that something correlates with something else--for example, [satisfaction with ones friendships is correlated with wellbeing](https://psycnet.apa.org/record/2019-64493-001) or [prejudice is correlated with endoresement of stereotypes towards a group](https://www.sciencedirect.com/science/article/abs/pii/0147176796000260)--is to say that those things *tend* to go together. Not everyone who feels great satisfaction in their friendships will report greater wellbeing than anyone with less social satisfaction, but there is some tendency for the two to go together on the whole.

Of course, these kind of correlations aren't just facts found lying around in nature; they are empirical findings produced by researchers. All the findings you learn about in the social psychology lecture (and beyond) are the product of research procedures. Researchers decide what psychological constructs they want to investigate; how to measure those constructs; what statistical analyses are appropriate; and what conclusions may be drawn. There are strengths, limitations, and trade offs involved in every decision along the way.



### Step 1. Examine the data and identify your variables

```{r}
#| include: false
library(tidyverse)
library(anesr)

data(timeseries_2020)

timeseries_2020_doc <- timeseries_2020 |> 
  map_chr(~attr(.x, "label")) |> 
  data.frame(question = _) |> 
  rownames_to_column(var = "id")

budget_vars <- timeseries_2020_doc |> 
  filter(str_detect(question, "Budget") | str_detect(question, "Abortion") | str_detect(question, "citizenship")) |> 
  filter(str_detect(question, "SUMMARY"))

budget_var_list <- budget_vars |>
  mutate(li = glue::glue("<li>{question} ({id})</li>")) |> 
  pull(li)


timeseries_2020 |> 
  haven::zap_labels() |> 
  select(concern_job = V201540, # higher scores: more worried
         concern_financial = V201594, # higher scores: less worried ***
         concern_losing_health = V201621, # higher scores: more worried
         concern_paying_health = V201622, # higher scores: more worried
         concern_terrorist = V202358, # 1 = extrememly; 5 = not at all ***
         concern_country = V201120, # 1 = not at all; 5 = extremely
         budget_social_security = V201302x,
         budget_schools = V201305x,
         budget_border = V201308x,
         budget_crime = V201311x,
         budget_welfare = V201314x,
         budget_buidling = V201317x,
         budget_poor = V201320x,
         budget_environment = V201323x,
         ) |> 
  mutate(across(everything(), ~ifelse(. < 1, NA, .))) |>
  mutate(concern_financial = 6 - concern_financial,
         concern_terrorist = 6 - concern_terrorist) |>
  mutate(across(contains("budget"), ~ 6 - .)) |>
  cor(use = "pairwise")

# cor(budget, use = "pairwise")

# Support for policies that reduce others' freedoms
# `r paste("<ul>", paste(budget_var_list, collapse = ""), "</ul>")`


# trust
timeseries_2020 |> 
  haven::zap_labels() |> 
  select(concern_job = V201540, # higher scores: more worried
         concern_financial = V201594, # higher scores: less worried ***
         concern_losing_health = V201621, # higher scores: more worried
         concern_paying_health = V201622, # higher scores: more worried
         concern_terrorist = V202358, # 1 = extremely; 5 = not at all ***
         concern_country = V201120, # 1 = not at all; 5 = extremely
         state_of_economy = V201324, # 1 = very good; 5 = very bad
         trust_federal_government = V201233, # 1 = always; 5 = never
         trust_people = V201237) |> 
  mutate(across(everything(), ~ifelse(. < 1, NA, .))) |> 
  mutate(concern_financial = 6 - concern_financial,
         concern_terrorist = 6 - concern_terrorist) |>
  mutate(across(contains("trust"), ~ 6 - .)) |>
  cor(use = "pairwise")

```

The dataset we will use is from the [American National Election Studies (ANES)](https://electionstudies.org/), academic surveys of voters in the United States conducted before and after every presidential election, going back to the 1940s. Specifically, for this project we will use data collected around the 2020 election, since it's the most recent survey.

The kind of correlation analysis you will perform examines whether two constructs are related. The full dataset contains more than 1,000 questions reflecting various constructs. Since this is your first project I am going to constrain your choice. You will investigate how perceived threats are associated with trust. Does distrust of the government and/or other people tend to go together with feeling threatened in some way?

One of your variables will be a question assessing __perceived threat__:

- How worried are you about losing your job in the near future? (`V201540`)
- So far as you and your family are concerned, how worried are you about your current financial situation? (`V201594`)
- How concerned are you about losing your health insurance in the next year? (`V201621`)
- How concerned are you about being able to pay health care expenses for you and your family in the next year? (`V201622`)
- How worried do you feel about how things are going in the country? (`V201120`)
- What do you think about the state of the economy these days in the United States? (`V201324`)
- How worried are you that the United States will experience a terrorist attack in the near future? (`V202358`)

Your second variable will be a question about __trust__:

- How often can you trust the federal government in Washington to do what is right? (`V201233`)
- How many of the people running the government are corrupt? (`V201236`)
- Generally speaking, how often can you trust other people? (`V201237`)

To see exactly how these constructs were measured you will look up the variable IDs (the codes beginning with V in parentheses above) in the [Codebook](https://electionstudies.org/wp-content/uploads/2022/02/anes_timeseries_2020_userguidecodebook_20220210.pdf).


### Step 2. Read relevant research

Real research doesn't happen in a vacuum; research plans and expectations should be informed by what has come before. Therefore once you know which variables you will analyze, you will see what other researchers have found about these (or related) constructs.

A real research project would involve an exhaustive literature review, in which you attempt to find and understand all the research relevant to your question. Since this project is just for practice and our time is limited, you don't need to read everything; this paper should give you an idea of what has been found:

::: {.references}
<!-- Rickert, E. J. (1998). Authoritarianism and economic threat: Implications for political behavior. *Political Psychology, 19(4)*, 707-720. <https://doi.org/10.1111/0162-895X.00128> -->

<!-- Feldman, S., & Stenner, K. (1997). Perceived threat and authoritarianism. *Political psychology, 18(4)*, 741-770. <https://doi.org/10.1111/0162-895X.00077> -->

Schlipphak, B. (2021). Threat perceptions, blame attribution, and political trust. *Journal of Elections, Public Opinion and Parties, 34(1),* 59–78. <https://doi.org/10.1080/17457289.2021.2001474>

<!-- Navarro-Carrillo, G., Valor-Segura, I., Lozano, L. M., & Moya, M. (2018). Do economic crises always undermine trust in others? The case of generalized, interpersonal, and in-group trust. Frontiers in psychology, 9, 1955. <https://doi.org/10.3389/fpsyg.2018.01955> -->
:::


### Step 3. Articulate your design and hypothesis

By this point you should be able to state your:

- __Operational definitions__ (that is, the specific questions that participants were asked and how they could answer, per the codebook)
- The __constructs__ that those operational definitions measure (i.e. does the question measure perceived threat *in general*? Or some more specific form of perceived threat?)
- Your __hypothesis__

Your hypothesis is a formal statement of your expectation about how your constructs are (or aren't) associated, and it will be tested quantitatively by calculating a correlation statistic.

The main question that your hypothesis addresses is: do you think the two variables will be significantly correlated? That is, will you find an association consistent enough that it doesn't just seem to be attributable to chance variation in the data?^[Even random data will produce spurious correlations by chance some of the time; see [spuriouscorrelations.com](https://spuriouscorrelations.com#stat897f4cbec4629379cd566c68c3f40c5f)]

If you do expect a significant correlation, you should also specify whether you expect it to be positive or negative, and how strong you expect it to be (i.e. weak, moderate, strong; see [Appendix B](appendix-correlation.html#sec-cor-effect-size)).


## To do for next time

Read another paper. The more detailed your understanding of the existing research, the better you will be able to interpret the results of your analysis.

::: {.references}
Navarro-Carrillo, G., Valor-Segura, I., Lozano, L. M., & Moya, M. (2018). Do economic crises always undermine trust in others? The case of generalized, interpersonal, and in-group trust. *Frontiers in psychology, 9,* 1955. <https://doi.org/10.3389/fpsyg.2018.01955>
:::
