# Lab 8: Writing the Introduction {.unnumbered}

## Key ideas

- Style and contents of an APA Introduction section
- How to frame previous findings to create a coherent and compelling justification
- APA style for citations & references


By now, you should have settled on your proposed design (though you may still be refining the details in response to collaboration with your partner(s) and guidance from Prof. Brotherton and your TA). Now you will begin to draft your complete lab paper, one section at a time. Instruction in class this week will focus on writing good APA-style Introduction section.

There are two major components of APA style. First, there are the nitty-gritty aspects of formatting the document itself, such as how to format the title page, running head, headings of different levels, figures, page numbers etc. The APA produces a manual which details exactly how to do this. However, the conventions change from time to time; the APA style guide is now in its 7th edition, published in October 2019. Because these formatting conventions are arbitrary and subject to change, I see them as relatively unimportant for our purposes. If you won’t be writing any more psych research articles, it’s not worth your time learning this stuff; if you will then you’re better off just using a current template when starting your documents—word processors like Word and Google Docs offer such templates built-in. I will make a Google Doc template specially tailored for this lab available.

One exception, however, is for citations and references. Since you are writing a scientific document based on existing research, it is important to cite that existing research according to the conventions of the field so that your sources can easily be checked by any interested reader. So while you can largely ignore fiddly formatting details, you will have to make an effort to use the correct citation style (or let a reference manager app like Zotero do the work for you; see [Appendix -@sec-zotero]<span class="exclude-from-html">, p. \pageref{sec-zotero}</span>.

The second component of writing an APA-style research article is the content. For our purposes this is much more important than arbitrary formatting rules. You must ensure that all the expected content is present in your work; that unneeded content is not present, so as not to distract or take away from the clarity and coherence of your writing; and that it is communicated in the tone expected of a psychological research article. The assignment description for each draft section will give an outline of required content, and you will find more advice and tips in [Appendix @sec-writing]<span class="exclude-from-html">, p. \pageref{sec-writing}</span>.



## Assignment

You will submit a draft of your Introduction section. This will be based on the literature review you have already written, but it may require some changes of emphasis, style, and structure. The general structure of a good APA-formatted Introduction is as follows:

- The first paragraph should introduce your broad area of research, emphasizing why it is a question of interest to psychologists, and, in a few sentences, summarizing the gist of existing research and how your proposed study would add to our understanding of social psychology.
- The main body of the Introduction is your literature review. Identify current theories relevant to the topic at hand, and present an overview of the findings of other researchers who have tried to answer similar questions. 
    - You should include at least 4 existing studies that relate to your question. 
    - They may or may not all require the same depth of description—e.g. if your methodology is very close to a particular previous study, it would require a more thorough description than a previous study for which the methodology is less directly relevant to your project.
    - The key is to make this a logically-flowing argument rather than a simple list of studies. Make sure each paragraph focuses on a single theme (which might be one study or more than one related study), and that each paragraph also transitions from and to the next by pointing out how the studies/theme relates to the others, and how they contribute towards your own research proposal.
- The last paragraph should briefly sum up your literature review, and state the question you are trying to answer. What are your specific hypotheses or expectations?
- You should be framing this as a gap in the literature you just outlined, or a necessary extension of some existing study.


## Notes {.exclude-from-html}

\cleartoleftpage
