# Lab 3: Ethics and Design {.unnumbered}


## Key ideas

- Asking questions that psychological research can answer
- Observing and measuring behavior
- Researcher influence over outcomes
- Pre-registration of research methods
- Informed consent and deception


As an introduction to social psychological thought, methods, and ethical considerations, this session will focus on Stanley Milgram’s research on obedience to authority, conducted in the 1960s. This is one of the most famous studies in the history of social psychology to ostensibly show the power of external situations over individuals’ choices. It’s well known, but not necessarily well understood by people who haven’t studied it in depth. In fact, over the years it has been misconstrued in many psychology textbooks. A detailed discussion and critique can teach us about the approaches, methods, and challenges of psychological inquiry, and the influence of both situations and individuals’ personality and preferences on behavior. It is also revealing about the history and evolution of psychology as a field of research, and the development of ethical guidelines for research with human participants.


## Suggested reading

::: {.references}
\hangindent=0.7cm Milgram, S. (1963). Behavioral study of obedience. Journal of Abnormal and Social Psychology, 67(4), 371.

\hangindent=0.7cm Haslam, S. A., & Reicher, S. D. (2012). Contesting the “nature” of conformity: What Milgram and Zimbardo's studies really show. PLoS Biology, 10(11), e1001426.

\hangindent=0.7cm Reicher, S. D., Haslam, S. A., & Smith, J. R. (2012). Working toward the experimenter: Reconceptualizing obedience within the Milgram paradigm as identification-based followership. Perspectives on Psychological Science, 7(4), 315-324.
:::




## Assignment

You will write a summary of a second published research paper. The rubric will be largely the same as before, but you should additionally begin drawing connections between this and the previous paper you summarized.
