---
toc: true
toc-depth: 3
---

# Lab 1: Course Overview {.unnumbered}

## Course details

Professor: Dr. Rob Brotherton (<rbrother@barnard.edu>)   
Office hour: Monday 10-11AM, Milbank 415M


### Section 001

Time & venue: Wednesday 10:10-1PM, Milbank 410  
Teaching Assistant:  
TA office hour:  

### Section 002

Time & venue: Wednesday 1:10-4:00PM, Milbank 410  
Teaching Assistant: Farhana Tanee (<fkt2108@barnard.edu>)  
TA office hour:  


## Schedule

```{r}
#| echo: false

schedule <- tibble::tribble(
  ~"Date", ~"Lab Topic", ~"Assignment", ~"%",
  "1/19", "No lab first week of classes", "Note: Most assignments are due 5pm the day after class. Exceptions are in italics.", "-",
  "1/19", "No lab first week of classes", "Note: Most assignments are due 5pm the day after class. Exceptions are in italics.", "-",
)

dates <- seq.Date(from = as.Date("2022-01-18"), to = as.Date("2022-05-01"), by = "week")

topics <- c("No lab first week of classes",
            "Introduction & Overview",
            "Project planning",
            "Ethics & design",
            "Measuring social psychological constructs",
            "Correlational designs",
            "Experimental designs",
            "Experimental designs continued",
            "Spring Break",
            "Writing the Introduction section",
            "Finalizing methods",
            "Reporting results",
            "Interpreting findings",
            "Presentations",
            "Final paper workshop")


assignments <- c("Note: Most assignments are due 5pm the day after class. Exceptions are noted.",
                 "Class participation (no submission; graded across the semester)",
                 "Paper summary 1",
                 "Paper summary 2",
                 "Paper summary 3",
                 "Paper summary 4",
                 "Brief lit review",
                 "Brief project proposal",
                 "-",
                 "Introduction draft",
                 "Method draft",
                 "Planned Analysis draft",
                 "Discussion draft",
                 "Presentation (submit slide before class)",
                 "Final paper & response letter")

weights <- c("-",15,5,5,5,5,5,5,"-",5,5,5,5,5,30)

# sum(as.numeric(weights), na.rm = TRUE)

schedule_df <- cbind("Date" = format(dates, format = "%m/%d"), "Lab topic" = topics, "Assignment" = assignments, "%" = weights)

knitr::kable(schedule_df)

```


## Lab overview

This lab is designed to offer experience participating in, reading, critiquing, and proposing research addressing social psychological phenomena. The lab will usually be taken concurrently with PSYC-BC2138 Social Psychology Lecture, and will expand upon the methodological and analytic issues introduced there, as well as giving you the opportunity to explore in greater depth a topic of your choosing from within (or beyond) those covered in the lectures by proposing your own original research project.


### Structure of the semester

In the first half of the course you’ll be finding, reading, and summarizing published research papers that may be relevant to your project, and working up a rough proposal. In class we’ll demonstrate and analyze the methodological and analytic approaches commonly employed in social psychological research, giving you the foundation upon which to build your research proposal. 

In the second half of the course you’ll draft each section of your proposal paper in turn before submitting the final report. In class we’ll focus on refining your proposed methodology and constructing an effective research paper.


### Class format & participation

Labs are substantially more interactive and discussion-based than the traditional lecture format, and depend on everyone’s participation. Your active participation across the semester will therefore contribute a substantial portion of your grade. 

If you have questions, thoughts, or ideas you want to share, feel free to do so at any time (while keeping within the bounds of polite conversation, obviously--don't interrupt or talk over other people! But do feel free to respond to others without having to raise your hand or wait to be called on). Everyone will get the most out of this lab when the discussion can develop organically and everyone feels free to be part of the conversation if & when they have something to add.

Being part of the in-person discussion is one obvious way to participate, but it’s not the only way. Different people have different styles of participation, and the lab is designed to try and accommodate and encourage different approaches (as well as allowing for the greater-than-usual possibility of missing class for health reasons). Your level of engagement with your project partner(s), your TA and Prof. Brotherton as you work through your project is also an important form of participation. You can also participate by coming to office hours.

At a minimum, I’ll be looking for some form of participation (loosely defined) from you every week; higher participation grades will be earned through regular, enthusiastic, productive participation (note that quality is more important than quantity).


### The research proposal

The final paper for this lab will be a Research Proposal paper. Producing this will be an iterative process; each assignment will build on the previous ones until by the end of the semester you have a complete research proposal paper.

Your proposed study can be on any social-psychological topic of your choosing. However, your proposed research should be an extension of previous research, not an exact replication of another existing study, but not an entirely new question either. Proposed studies will use one of the basic methodological approaches that we will cover in the lab this semester or one that you discuss in the lecture. For example, you may propose the development and validation of a new scale ([Lab 4](./lab-4.html)); a correlational study looking at relationship among constructs ([Lab 5](./lab-5.html)); or an experimental study manipulating an independent variable and measuring its effect on a dependent variable ([Lab 6](./lab-6.html)).

The project you complete will be a research proposal. You will propose a viable piece of research that could, in theory, be conducted by you or any other researcher—but you won’t actually collect data for it as part of this lab. There are a number of reasons for this. Logistically, to achieve sufficient statistical power (see [Appendix @sec-power]<span class="exclude-from-html">, p. \pageref{sec-power}</span>) social psychological studies often require sample sizes larger than we could feasibly collect as part of this lab. Running an underpowered study is a waste of your and your participants’ time. In addition, merely proposing a study without having to run it allows you to be more ambitious in the kind of research you can propose, which can allow you to explore questions of greater scope and meaning. For students who may be considering a career in academic psychology or another science, proposing studies will be an essential aspect of obtaining grants and fellowships to allow you to conduct that research. Additionally, even beyond the context of obtaining funding for proposed research, recent years have seen a move towards pre-registration of research designs within the field of psychology more broadly. This means creating and publishing a complete plan for your research before collecting the data. We’ll discuss the value of this as part of this and the coming lab sessions. By proposing a study here, you’ll be essentially pre-registering a potential study design.

A few students each semester mention feeling disappointed not to get to collect data for their project. It’s understandable, but in addition to the issues mentioned above, I’d urge you to think about how much work that would add to the course, and how it would add comparatively little value to your learning experience. Not having to collect data frees us to focus on refining all the details of your study in the limited time we have available, therefore developing a deeper understanding of the crucial issues on which all successful research depends: theoretical, methodological, and interpretative rigor. If you really want to experience collecting and analyzing real data, I’d suggest aiming to run your proposed study as part of an Independent Project in future, for which you can earn 4 to 8 credits depending on whether you complete it over 1 or 2 semesters.


### Workload

As a general rule for the amount of time students should expect to commit to classes, the college suggests three hours per week in or outside of class per credit. Since this class is worth 1.5 credits, that corresponds to 4.5 hours per week, split between time in the classroom and time spent completing the associated assignments.


### Final Grades

Your final letter grade for the course is a product of your scores for each assignment, weighted as indicated in the class schedule, and determined according to the following boundaries:

    Letter grade:  A+ A  A-	B+ B  B- C+ C  C- D  F
    Numeric score: 97 93 90 87 83 80 77 73 70 60 <60



## Course Policies

### Attendance & timeliness

In-person attendance of each lab session is expected, except in emergencies. Normally it is departmental policy to remove students who miss more than two sessions from the course; however, given ongoing revisions to college-wide health-related policies, exceptions may be made. If you are feeling unwell, you should not come to class and notify me of nonattendance before class if possible. When you are attending, please arrive on time for class. Frequent lateness will impact your participation grade.

### Assignment deadlines & late policy

Assignments are listed in the class schedule next to the class session to which they correspond. Most assignments are due at 5pm the day after class. All assignments relate to your project proposal—the idea is to build this major piece of work incrementally over the course of the semester. The 5pm next-day deadline is necessary to allow time to provide substantive feedback to everyone in advance of the next assignment.

A grade penalty of 5 points will be applied for each day (or part thereof) that an assignment is late (up to a maximum of 6 days; work not submitted before the next lab will receive a score of zero). For example, if your work is A+ quality but is submitted a day-and-a-half late, you will only receive a B+. Due to time constraints, you may also not receive feedback on late work. 

This policy is intended to incentivize timely submission while easing the stress of genuine emergencies. When things come up that prevent timely submission you can prioritize accordingly, knowing that a small penalty on one assignment for this lab will not tank your final grade.

### Use of laptops / other devices

My intention is that this printed lab manual will serve as your primary source of reference and note-taking in class. Laptops will not be required and should not be used unless you have some exceptional need, which should be discussed with me in advance. Cell phones should be silenced.

### Academic integrity

Students are expected to follow the Barnard Honor Code, available at <https://barnard.edu/honor-code>.

Note that even though you may collaborate in lab and on the research proposal, you may not collaborate on written assignments. You must write your own reports. 

### Academic accommodations and general wellness

It is always important to recognize the different pressures, burdens, and stressors you may be facing, whether personal, emotional, physical, financial, mental, or academic. The faculty and administration recognize this, and are prepared to provide assistance to students in need. I encourage you to seek advice from your advisor, Dean, the [Center for Accessibility Resources & Disability Services (CARDS)](https://barnard.edu/disability-services), or [Barnard Health & Wellness](https://barnard.edu/health-wellness) as needed. Please let me know of any issues you wish to share with me that you feel are impacting your ability to complete the course to the best of your ability. Though it isn’t always easy, it is better to proactively seek help rather than letting problems build up.


## Notes {.exclude-from-html}

\cleartoleftpage
