# Lab 6: Project planning {.unnumbered}

In this lab, you will start your second project: conducting an ANOVA interaction analysis using the same ANES data as before. In this project you'll investigate how political partisanship and life experiences might interact to predict social trust.


### Goals

- Understand the purpose of ANOVA
- Identify variables for your analysis
- Search the literature to find relevant research
- Articulate your hypotheses


## Project overview

### Understanding ANOVA

ANOVA stands for <b>AN</b>alysis <b>O</b>f <b>VA</b>riance. It is a statistical procedure which quantifies the relative contribution of difference sources of variability (variability between groups and variability within groups) to understand whether there are differences *between* groups over and above what would be expected by chance (i.e, based on the random variability *within* the groups).

ANOVA will always have a single, continuous dependent variable (DV). ANOVA can have any number of independent variables (IV; also called factors), each with any number of conditions (also called levels). The design will be described as something like "a 3x5 ANOVA", which would mean that there were 3 factors with 5 levels each. 

__For this project, your design will be a 2x2 ANOVA, meaning 2 factors, each with 2 levels.__

#### Quasi-independent variables

Researchers often "manipulate" at least one of the IVs in a study, making it an "experiment." In this context, the name "independent variable" implies that the researcher randomly determines which experimental group a participant will be in; therefore, the manipulated variable is theoretically "independent" of other variables in the study. The ANES, however, consists only of survey data; there is no experimental random assignment.[^random-note] Categorical variables that are not randomly assigned are called *quasi*-independent variables; they can still be used to look for differences between groups of participants, but since participants' membership of a group is an existing characteristic of theirs rather than something randomly determined, it isn't truly "independent" of other variables.

It may sound like a limitation, but there are good reasons to use quasi-IVs in research. It isn't always possible or ethical to randomly assign group membership, yet there is still value in comparing existing groups. As an example, a participant's age can't be randomly assigned, but it is still often useful to compare different age groups to look for differences on some dependent variable. That said, there are important implications for causal inference that you should consider when it comes time to interpret your findings.

#### Main Effects & Interaction

For each (quasi)-IV in your design, you will examine its "main effect". That is, is that variable associated with a difference on the DV, ignoring the existence of the other IV.

However, the value of a factorial ANOVA design is in revealing the "interaction" between variables: does the effect of one (quasi)-IV depend on another (quasi)-IV? 

For this project, we will stick with the idea of trust: it will be the DV. One of the quasi-IVs will be an indicator of political ideology/partisanship. It makes sense that some types of social trust could depend on your political preferences (or something related, like whether your preferred political party is currently "winning"). But political affiliation isn't the only thing that could be associated with trust. Maybe one's life experiences also play a role. Having had, or not had, some particular experience might be associated with expressing more or less trust. But crucially, maybe the two variables *interact*: maybe the relationship (if any) between partisanship and trust depends on what kind of experience a person has had (or not had). It could be that an experience affects trust among people who lean one way but not people who lean the other.


### Step 1. Examine the data and identify your variables

#### Dependent variable

You dependent variable should be continuous (measured on a numeric scale). For this project, we will stick with the idea of trust. 

- How often can you trust the federal government in Washington to do what is right? (`V241229`)
- How many of the people running the government are corrupt? (`V241233`)
- Generally speaking, how often can you trust other people? (`V241234`)
- In general, how much trust and confidence do you have in the news media when it comes to reporting the news fully, accurately, and fairly? (`V241335`)

#### (Quasi)independent variables

The first of your quasi-independent variables will be some indication of participants' political preferences.^[There's a whole literature about ideology and partisanship and I don't expect you to get into the weeds with it, but I expect you'll have some thoughts about the various strengths/limitations of these few questions.]

- What political party are you registered with, if any? (`V241025`)
- Who did you vote for? (`V242067`)
- If you had to choose, would you consider yourself a liberal or a conservative? (`V241178`)

<!-- - Racial identity -->
<!-- - Gender identity -->
<!-- - Partisanship (stated; vote) -->
<!-- - Income -->
<!-- - Age -->
<!-- - Media -->
<!-- - Personal (in)security -->

Your second quasi-independent variable will be one of the "life experiences" that the ANES survey asks about:

  - What is the highest level of school you have completed or the highest degree you have received? (`V241463`)
  - Are you registered to vote? (`V241012`)
  - Are you currently living with a partner, or not? (`V241462`)
  - Do you personally know someone who moved to the U.S. from another country, or not? (`V242604`)
  - Among your immediate family members, relatives, neighbors, co-workers, or close friends, are any of them gay, lesbian, or bisexual as far as you know? (`V242508`)
  - Have you gone hunting or fishing in the past year, or not? (`V242605`)
  - Have you used public transportation in the past year, or not? (`V242606`)
  - Lots of things come up that keep people from attending religious services even if they want to. Thinking about your life these days, do you ever attend religious services, apart from occasional weddings, baptisms or funerals? (`V241439`)
  - Have you ever been arrested, or has that never happened to you? (`V242507`)
  - In the past 12 months, did you buy or boycott products or services based on the political values or business practices of that company? (`V242037`)
  - In the past twelve months, have you contacted a federal elected official, such as a member of Congress or the President, or someone on the staff of such an official? (`V242036`)
  - During the past 12 months, have you joined in a protest march, rally, or demonstration, or have you not done this in the past 12 months? (`V242029`)
  - During the past 12 months, have you ever gotten into a political argument with someone, or have you not done this in the past 12 months? (`V242033`) 
  - In the past 12 months, did you spend any time volunteering for any organization or association? (`V242035`)
  
  <!-- - Have you ever been bitten by a shark, or not? (`V242607`) -->


### Step 2. Find relevant research

Since your choice of variables is more open-ended, I can't point you towards particular papers like I did for the previous project. You'll have to think about your constructs and see if you can find relevant research. In particular, what psychological construct do you think your "life experience" variable might reflect or relate to?

In class, I want you to find at least 2 or 3 promising-looking sources, which you will read for homework over the next couple of weeks. For now, just read the abstracts to find papers that look most relevant.

#### What to look for

Published, scholarly journal articles detailing an empirical finding relevant to your variables of interest. This might be a paper reporting one or several individual studies that the researchers conducted, or it may be a review paper or meta-analysis.^[A meta-analysis pools the findings of many individual studies by different researchers into a single analysis.]

#### Where to look

##### [Google Scholar](https://scholar.google.com)

Google Scholar searches the full text of scholarly articles. It casts a wide net, searching across all disciplines, and including books and other materials in addition to journal articles, so will likely find many articles not very relevant to the topic as well as those that are relevant.

##### [APA PsycINFO](https://resolver.library.columbia.edu/ALD2284)

The link above should take you to PsycINFO, a database for scholarly psychology research (you can also search for `psycinfo` in a CLIO quicksearch). PsycInfo gives you the ability to do more focused searching than Google Scholar.

-   You can add many keywords and combine them with the Boolean operators `AND`, `OR`, and `NOT` by selecting them from the dropdown boxes.
-   You can select where your keywords should appear, i.e. in the title, abstract, or full text of articles. Selecting `Word in Major Subject Heading` can help narrow down your search to articles that are actually on the topic you're interested in (rather than just containing the keyword).



### Step 3. Articulate your design and hypothesis

As before, you should be able to state your:

- __Operational definitions__ (that is, the specific questions that participants were asked, per the codebook)
- The __constructs__ that those operational definitions measure
- Your __hypotheses__

In the context of a 2x2 ANOVA design, you will have three different hypotheses. For each IV, you will hypothesize the existence (or not) of a main effect; that is, do you expect to see a difference between the different categories of that IV by itself (ignoring differences on the other IV). In addition, you will have a hypothesis about the "interaction" of the two IVs; that is, do you expect them to have a *combined* effect? In more technical terms, do you expect that the effect of one IV depends on the level of the other IV?

## To do for next time

Read one of the papers you found. The more detailed your understanding of the existing research, the better you will be able to justify your choice of variables and interpret the results of your analysis.

[^random-note]: That's not *quite* true. Some elements of the survey are randomized, such as the order of certain questions or answer options. And the ANES often tests different versions of questions before including them in the full survey; answers to different versions of questions can be compared to check whether seemingly minor differences to wording substantively affect people's answers.
