# Lab 10: Project planning {.unnumbered}

My hope is that at this point you are feeling a sense of accomplishment at what you have achieved through the projects so far, but that you're also feeling a bit limited by the constrained limited choice of variables/topics you had. In this lab we'll begin the final project: you will execute a project of your own design, with the freedom to choose any variables you like from the full data set.


### Goals

- Decide on an analysis and identify the relevant variables
- Find some relevant research
- Articulate your hypotheses



## Project overview

For this project you have free choice of design and constructs. You may look at the correlation(s) between two (or more) variables, or you may use an ANOVA design to look at differences between groups based on categorical variables. The process for getting started planning your design is the same as before.


### Step 1. Decide on your constructs/operational definitions

The full ANES 2020 dataset contains more than 1,000 columns, each representing a different variable that was measured. To navigate this, see the [codebook](https://electionstudies.org/wp-content/uploads/2022/02/anes_timeseries_2020_userguidecodebook_20220210.pdf), or the [Methodology Report](https://electionstudies.org/wp-content/uploads/2022/08/anes_timeseries_2020_methodology_report.pdf#page=16) which organizes things into "modules". Not all of these are equally interesting from a social-psychological perspective, but you will find many questions that pertain to fundamental social-psychological concepts. Here are some suggestions--constructs the ANES data measures in some way that you might consider from a social psychological perspective:

- Feeling thermometers (affect towards various political actors/groups)
- Political knowledge
- Media consumption
- Authoritarianism
- Stereotypes
- Policy preferences
- Conspiracy beliefs
- Religiosity
- Life experiences


### Step 2. Find relevant research

You should search the literature (using Google Scholar or PsycINFO, as before) and find at least one published research paper that pertains to the constructs you want to look at.


### Step 3. Articulate your hypotheses

As before, you should be able to describe:

- The social psychological constructs you are interested in
- The operational definitions used to measure those constructs in the ANES survey
- You hypothesis about how your constructs relate
